### ISSUE TITLE
Niches pages and ALTs for their images

### ISSUE THREAD

**Issue by craigfisk** [Marmalade-ai/company-website#94] opened 2021-08-05 03:20 UTC
Probably we should get the menus and pages for the 3 niches built now, and deal with expanding the content in the body of each page later. 
To note about this version in the "Niches pages" (see below):
- 1st image in UX Design page is changed.
- Full-sentence tags are included for all images.
- "Extra credit"? Could use the ALT text also for captions in each case. There is a handy MDN (Mozilla Developer Network) page on how to use the <caption> tag in HTML5: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption

In Marmalade > website > "Niches pages" (https://docs.google.com/document/d/1CXoZ2ZO9mcolbg017W38fZoY0aSJUwlMaG-9HowqvY8/edit)

**Comment by jimtyhurst** [comment] 2021-08-07 22:24
I am closing this Issue, because it is a duplicate of Issue #55. I copied some of the material from this description to that issue, so that Issue #55 has all of the requirements from this issue.

Regarding the MDN reference to the [&lt;caption&gt;](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption) element:
- [&lt;caption&gt;](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption) only applies as a child to a [&lt;table&gt;](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table) element, so it is not useful for our presentation of images.

**Closed by jimtyhurst** 2021-08-07 22:24 UTC
Labels: duplicate, enhancement
